//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControleReceita.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class fin_categoria
    {
        [Key]
        [Column(Order = 1)]
        public int CAT_CODIGO { get; set; }
        public string CAT_NOME { get; set; }
        public string CAT_STATUS { get; set; }
        public string CAT_TIPO { get; set; }

    }
}
