//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControleReceita.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Relfin_credito_debitoAnualDto
    {
        

        public string AnoPesquisa { get; set; }

        public Decimal TotalCreditoAnual { get; set; }
        public Decimal TotalDebitoAnual { get; set; }
        
    }
}
