//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControleReceita.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Relfin_credito_debitoDto
    {
        public int FCD_CODIGO { get; set; }
        public DateTime MesAnoPesquisa { get; set; }
        public string CAT_TIPO { get; set; }
        public int CAT_CODIGO { get; set; }

        public string CAT_NOME { get; set; }

        public Decimal FCD_VALOR { get; set; }

        public string AnoPesquisa { get; set; }

        public Decimal TotalCreditoAnual { get; set; }
        public Decimal TotalDebitoAnual { get; set; }
        
    }
}
